---
title: "tidycoral"
author: "Ingrid"
date: "March 13, 2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
## libraries

library(tidyverse)
library(janitor) #install.packages('janitor')
library(skimr) # install.packages('skimr')
library(stringr) # added when we needed it for benthic data

## data filepaths/urls ----

## benthic data
benthic_url <- 'https://www.nodc.noaa.gov/archive/arc0054/0104255/1.1/data/0-data/cd08/100308OaAla03m.CSV'

## buoy data
buoy_url <- 'http://www.ndbc.noaa.gov/view_text_file.php?filename=mokh1h2010.txt.gz&dir=data/historical/stdmet/'
```

# Benthic Data

```{r}
benthic_raw <- read.csv(benthic_url)
head(benthic_raw)
```
```{r}
benthic <- benthic_raw %>% 
  janitor::clean_names()
names(benthic)
# Janitor function auto corrects bad title names, eg with spaces and capital letters. Pretty powerful!
```
```{r}
benthic <- benthic %>%
  select(id_name, point, x, y, id_date)

head(benthic)
```

```{r}
#strings are just a sting of characters, things you put quotes around
benthic <- benthic %>%
  mutate(date = stringr::str_remove_all(id_date, "#"))

head(benthic)
```

```{r}
skimr::skim(benthic)
```

```{r}
unique((benthic$id_name))
```
```{r}
ggplot(benthic, aes(x = date, fill = id_name)) +
  geom_bar()

```
Read in the data
# Buoy Data
```{r}
buoy_raw <- read_csv(buoy_url)
head(buoy_raw) 
#didn't work, it's a fixedwidth table
```
```{r}
buoy_raw <- read_table2(buoy_url)
head(buoy_raw) 
```

```{r}
buoy <- buoy_raw

```

```{r}
## 1. overwrite column names
names(buoy) <- str_c(names(buoy),                  ## current header
                  buoy %>% filter(`#YY` == "#yr"), ## row1 -- don't say buoy[1,] 
                  sep = "_")                       ## separate by `_`

## inspect
names(buoy) ## Looks a lot better
```
```{r}
## 2. clean up a bit more to get rid of the `#`s and the `/`s. 
names(buoy) <- str_replace_all(names(buoy), "#", "")  # replace `#` with nothing 
names(buoy) <- str_replace_all(names(buoy), "/", "_") # replace `/` with `_`

## inspect to make sure it worked
names(buoy)
```

```{r}
## 3. remove redundant row with units (!= means every row but the one starting with #yr should remain)
buoy <- buoy %>%
  filter(YY_yr != "#yr")
head(buoy)
```
```{r}
ggplot (buoy, aes(WTMP_degC)) +
geom_bar() +
  theme(axis.text.x = element_text(angle = 90)) +
  theme_bw()
#theme to determine  angle of axis values 
```

```{r}
#converge the dates between the two data sets (benthic and buoy)
buoy <- buoy %>%
  unite(date, c(YY_yr, MM_mo, DD_dy), sep = "-")

head(buoy)
```
```{r}
#Join the 2 datasets together!


bb_join <-  left_join(benthic, buoy, by = "date")

#head (bb_join) realize need to check the data and make sure it joined properly

bb_join %>% select(id_name, x, y, date, hh_hr, mm_mn, WTMP_degC) %>%
  head()
```

```{r}
head(buoy,20)
```

```{r}
head(benthic)
```
```{r}
buoy_daily <- buoy %>%
  mutate(temp_clean = as.numeric(gsub("999.0", NA, WTMP_degC))) %>% #first need to get rid of 999's
  group_by(date) %>% #then group by date 
  summarise(mean_temp = mean(temp_clean, na.rm=T))#then get mean temps
head(buoy_daily)

```

```{r}
#OR
#buoy_daily <- buoy %>%
 # mutate(temp_clean = gsub("999.0", NA, WTMP_degC))) %>% #first need to get rid of 999's
  # mutate(temp_clean = as.numeric(temp_clean)) %>% #make it numeric
  #group_by(date) %>% #then group by date 
  #summarise(mean_temp = mean(temp_clean, na.rm=T))#then get mean temps
#head(buoy_daily
```


```{r}
bb_join <-  left_join(benthic, buoy_daily, by = "date")
```

